### PR TITLE
Throws an exception if the parser fails. [8057]

### PR DESCRIPTION
**Pull request by LuisGP**
This PR adds an exception throwing if the parser fails.

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/58/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/59/)

**Comment by vmanchal1** [comment]
How do I fix the cause of this exception. I have been using `soss_v2` out of the branch `features/xtypes-dds` for a few months now. Recently, I had to pull the latest branch and make some changes to support ROS2 Foxy as we have upgraded from ROS2 `eloquent` to `foxy`. 

Now, soss fails to parse a custom ROS2 msg type. I am sure nothing has changed on the custom ROS2 msg. How do I fix this?

**Comment by jamoralp** [comment]
Hello @vmanchal1, we have a still unmerged pull request for Foxy support: https://github.com/eProsima/soss_v2/pull/33 please check it out

**Comment by vmanchal1** [comment]
@jamoralp Thank you for the response. I have cherry-picked the changes from #33 and still see this runtime error.

**Comment by rokel** [comment]
I see the same runtime parsing error when trying to use `sensor_msgs/JointState`.

Deleting the `@verbatim` comment blocks in the generated IDL code seems to fix the issue, so I would guess it's an issue with escaping comment text.

**Comment by rokel** [comment]
It turns out the runtime error in this instance is specifically due to single quote characters in .msg comments (e.g. [Time.msg](https://github.com/ros2/rcl_interfaces/blob/foxy/builtin_interfaces/msg/Time.msg)). 

I'm not sure whether the fault is in `rosidl_adapter` for not escaping these in the IDL, or `xtypes` for not accepting them.

**Pull request merged**
