### PR TITLE
Added ros2 documentation design.

### PR DESCRIPTION
**Pull request by lemunozm**

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/36/)

**Comment by LuisGP** [comment]
I miss the `...` in the list of `so` files in the same way it is present in the list of `h`/`cpp` files.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/40/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/43/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/45/)

**Pull request merged**
