### PR TITLE
Skip blank Services' names

### PR DESCRIPTION
**Pull request by laura-eprosima**

### CODE REVIEW

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/87/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/116/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/117/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/121/)

**Review by jamoralp — APPROVED** [review]
Approved, since #41 tests have passed and already include this fix.

**Pull request merged**
