### PR TITLE
Refs #6981 Added "paths" to types. 

### PR DESCRIPTION
**Pull request by LuisGP**
This PR adds the possibility to specify include paths for the parser's preprocessor.
It modifies the whole "types" section in the yaml, so all examples and tests should be adapted.

Old format:
```yaml
types:
    - idl: >
        struct A...

    - idl: >
          struct B...
```

New format:
```yaml
types:
    paths: [ "path/to/include" , "another/path" ]
    idls:
        - >
            struct A...

        - >
            struct B...
```

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/33/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/34/)

**Comment by LuisGP** [comment]
Jenkins job updated to download thirdparties before call colcon.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/35/)

**Pull request merged**
