### PR TITLE
Fix compile error

### PR DESCRIPTION
**Pull request by jacobperron**
Include <cassert> header to resolve the following error:

    MiddlewareInterfaceExtension.cpp:98:5: error: ‘assert’ was not declared in this scope
       98 |     assert(_directory.is_absolute());
          |     ^~~~~~

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/82/)

**Comment by jacobperron** [comment]
I just noticed a similar fix landed upstream: https://github.com/osrf/soss/commit/f43a596149109c857c0a86a64591d0e8db779264

**Comment by jamoralp** [comment]
Good morning, we are retaking the maintenance of our Jenkins test server infrastructure (it had some big performance problems due to a buggy extension that was used). As soon as it is properly configured, I will re-launch these tests and merge this. Thanks!

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/92/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/98/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/99/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/100/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/101/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/102/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/103/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/104/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/105/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/107/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/108/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/109/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/110/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/111/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/112/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/113/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/114/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/115/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/124/)

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/125/)

**Comment by jamoralp** [comment]
Ok, this took a while but it finally seems that our CI is working properly. Therefore, I'm merging this now. Thanks for the contribution @jacobperron !

**Review by jamoralp — APPROVED** [review]

**Pull request merged**
