### PR TITLE
Support for ROS2 Foxy

### PR DESCRIPTION
**Pull request by jamoralp**

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/72/)

**Comment by jamoralp** [comment]
Tests should be run on Foxy before merging. Right know, they are being run on ROS 2 Crystal.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/75/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/76/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/soss/77/)

**Review by richiware — APPROVED** [review]

**Pull request merged**
